### ISSUE TITLE
AI PR 코드 리뷰 기능

### ISSUE THREAD

**Issue by Lieslot** [SWM-Codection/Codection-AI-Interface-Server#1]
## PR 리뷰 기능

---
- [x] 파일의 내용을 OpenAI API로 넘겨서 결과를 받아오기
- [x] 각 파일마다 Thread(OpenAI API)를 생성하여 별개의 컨텍스트 윈도우 생성 후 gpt assistant에게 리뷰를 요청해서 받기 ->  프롬프트 엔지니어링에 대해선 좀 더 연구가 필요할듯 싶어 일단 파일 별로 리뷰 결과를 받음.
- [ ] 각 스레드의 리뷰 결과를 받아서 파싱하여 데이터 베이스 PR comment로 저장
- [ ] gitea와 서버와 연동할 메세지 큐를 설정해보기 

## 생각해볼만한 부분

각 부분에 대해서 본인의 생각을 말씀해주세요. 여기에 제안되지 않은 방식이라도 좀 더 좋은 방식이 생각 나시면
제시해주세요.

---
1. 풀 리퀘스트에 새로운 PR이 날아오면 어떻게 처리해야하는가?
    - 맨 처음에 생성될 때는 자동으로 달아주고 리뷰어나 리뷰이가 직접 리뷰 생성 버튼을 눌러서 리뷰를 새롭게 만드는 방식(단 한 번 생성하면 새로운 커밋이 생성될 때까지 못함.) <- 현재는 이 방식을 생각 중.
    - 매번 커밋이 생길 때마다 gitea 서버에서 API 서버로 리뷰 요청을 날려서 코드 리뷰를 처리하는 방식

2. OpenAI의 서버 문제로 요청이 완료되지 않고 Time Out이 발생하면 어떻게 처리하는가?
    - 이진수 백오프 방식
    - 사용자가 나중에 알아서 리뷰 생성 버튼을 눌러서 요청하게 만든다. <- 현재는 이 방식을 생각 중

3. API 서버에서 데이터 베이스에 PR Comment를 저장하는 방식에 대해

   - 일단 이 API 서버에서 PR 커멘트를 데이터베이스에 직접 넣는 방식을 생각해봤는데 API 서버에서 DB를 접근해서 저장하는 게 맞는지 모르겟음..
   - 그렇다고해서 gitea에 다시 돌려 보내서 데이터 베이스에 저장하는 방식도 좋은 방식인지는 잘 모르겠음.

**Comment by cloudchamb3r** [comment]
1. 새로운 PR 이 날라오는건, ai 서버에서 판단하기는 힘들어 보입니다. 이부분은 gitea 측에 전면적으로 맡기고, gitea 쪽 코드에서 ai 서버에 요청을 두는게 좋아보입니다. 1번 내용을 잘 이해는 못했지만, 2번 내용은 커밋마다 코드 리뷰 처리는 좀 과할거같다는 생각도 듭니다. 

2. 이진수 백오프 방식이 1, 2, 4, 8... 등으로 텀을 두면서, 계속 요청을 날리는게 맞을까요? 보통  지수 백오프라고 합니다. 서버 에러가 뜬다면 서버 에러가 뜬다고 사용자에게 표시하고, 에러 상황에 대해 사용자가 재 시도를 할수 있게끔 하는게 좋아보입니다

3. api 서버에서 굳이 gitea db 에 write 하는건 별로 좋은 생각은 아닌거 같습니다. 말씀하신대로 gitea로 돌려보내 데이터베이스에 저장하는 방식도 좋은지는 한번쯤 생각해봐야겠지만, 전 후자의 방식이 조금 더 괜찮아보입니다

**Comment by Lieslot** [comment]
아 제가 설명이 좀 부족했네요. 1번의 경우 PR 커밋이 올라오면 gitea 서버에서 API 서버로 요청(메세지큐든 REST API든)을 날리는 방식을 생각하고 있습니다.
